### ISSUE TITLE
1 suggestion and 1 issue

### ISSUE THREAD

**Issue by PQCraft** [SapphireVideos/ironix#4]
The readme is lacking a description lol
Also, since this is in Java, CSS, and HTML I assume this is supposed to run in a browser. You can actually host this as a webpage as a gtihub site (`ironix.github.com`) by going to the 'Pages' tab in settings.

**Comment by SapphireVideos** [comment]
Thanks for the suggestion!
I will commit an update with a new README really soon. And about the webpage, because the way it works, GitHub Pages will not work.
